title: Campus Careers
description: Connecting UH MÄnoa students with internship and job opportunities.
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/campus-careers
gems:
  - jekyll-mentions
